import fs from 'node:fs';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const repo=new URL('../',import.meta.url).pathname.replace(/^\/([A-Za-z]:)/,'$1').replace(/\/$/,'');
const require=createRequire(repo+'/package.json');
const ts=require('typescript');
const source=fs.readFileSync(repo+'/app/api/prices/priceStore.ts','utf8');
const code=ts.transpileModule(source.slice(source.indexOf('export async function importManagedPriceItems')), {compilerOptions:{target:99,module:99}}).outputText.replace('export async function','async function');
let state, fail=false, calls=0;
const env={DB:{prepare(sql){return {sql,bind(...args){return {sql,args}}}},async batch(statements){calls++;const next=structuredClone(state);for(const st of statements){if(st.sql.startsWith('UPDATE'))next.forEach(x=>x.isActive=false);else {const a=st.args; const row={id:a[0],name:a[1],category:a[2],amount:a[4],isActive:!!a[9]};const i=next.findIndex(x=>x.id===row.id);if(i<0)next.push(row);else next[i]=row;}}if(fail)throw Error('database failure');state=next;}}};
const run=new Function('env','ensurePriceItemsTable','listManagedPriceItems','getImportMatchKey',code+'; return importManagedPriceItems;')(env,async()=>{},async()=>structuredClone(state),(n,c)=>`${c}::${n.trim().toLowerCase()}`);
const seed=()=>{state=[{id:'a',name:'A',category:'ultrasound',amount:100,isActive:true},{id:'b',name:'B',category:'ct',amount:200,isActive:true}];calls=0;fail=false;};
const row=(name,id)=>({id,name,category:'ultrasound',categoryLabel:'УЗД',amount:300,turnaround:'Уточнюйте',citoAvailable:false,citoSurcharge:0,aliases:[],isActive:true,sortOrder:0});
seed();assert.deepEqual(await run([row('Renamed','a'),row('New')]),{created:1,updated:1,hidden:1});assert.equal(state.find(x=>x.id==='b').isActive,false);assert.equal(calls,1);
seed();await run([row('A')]);assert.equal(state.filter(x=>x.isActive).length,1);assert.equal(state[0].id,'a');
seed();await assert.rejects(run([]));assert.equal(calls,0);
seed();await assert.rejects(run([row('A','a'),row('A')]));assert.equal(calls,0);
seed();fail=true;await assert.rejects(run([row('A','a')]));assert.equal(state[1].isActive,true);assert.equal(state[0].amount,100);
console.log('5 price synchronization scenarios passed');
